info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T16:38:56.663Z"}
info: Connected to the database. {"timestamp":"2022-06-25T16:38:56.716Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:10:33)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.UserRegistration (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:10:30)
    at _callee3$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:50:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/signUp 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-25T16:42:11.764Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T16:54:55.287Z"}
info: Connected to the database. {"timestamp":"2022-06-25T16:54:55.310Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T17:51:03.411Z"}
info: Connected to the database. {"timestamp":"2022-06-25T17:51:03.447Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/signUp 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-25T17:51:37.636Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee5$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:42:32)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogin (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:41:23)
    at _callee2$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:31:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-25T17:51:51.335Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee5$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:42:32)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogin (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:41:23)
    at _callee2$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:31:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-25T17:52:09.554Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T17:53:18.465Z"}
info: Connected to the database. {"timestamp":"2022-06-25T17:53:18.488Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee5$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:42:32)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogin (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:41:23)
    at _callee2$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:31:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-25T17:53:22.638Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:00:02.992Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:00:03.013Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:10:54.321Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:10:54.346Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:13:31.309Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:13:31.338Z"}
error: 
    status - 500 
    message - ReferenceError: email is not defined
    at _callee5$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:42:35)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogin (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:41:23)
    at _callee2$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:31:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-25T18:13:35.264Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:16:13.420Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:16:13.450Z"}
error: 
    status - 500 
    message - ObjectParameterError: Parameter "filter" to findOne() must be an object, got avi@gmail.com
    at model.Query.Query.findOne (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:2321:16)
    at Function.findOne (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:2267:13)
    at _callee5$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:41:21)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.userLogin (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:23)
    at _callee2$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:31:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-25T18:16:20.656Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:17:08.485Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:17:08.511Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:18:34.653Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:18:34.680Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:19:28.312Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:19:28.342Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-25T18:24:23.370Z"}
info: Connected to the database. {"timestamp":"2022-06-25T18:24:23.393Z"}
