info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T02:39:37.300Z"}
info: Connected to the database. {"timestamp":"2022-06-30T02:39:37.733Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T05:24:45.249Z"}
info: Connected to the database. {"timestamp":"2022-06-30T05:24:45.275Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T05:28:07.911Z"}
info: Connected to the database. {"timestamp":"2022-06-30T05:28:07.935Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T05:30:14.469Z"}
info: Connected to the database. {"timestamp":"2022-06-30T05:30:14.493Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T05:33:41.667Z"}
info: Connected to the database. {"timestamp":"2022-06-30T05:33:41.700Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T05:35:27.032Z"}
info: Connected to the database. {"timestamp":"2022-06-30T05:35:27.057Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T05:54:47.850Z"}
info: Connected to the database. {"timestamp":"2022-06-30T05:54:47.876Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T05:56:15.643Z"}
info: Connected to the database. {"timestamp":"2022-06-30T05:56:15.669Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T06:19:05.451Z"}
info: Connected to the database. {"timestamp":"2022-06-30T06:19:05.474Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T06:19:30.311Z"}
info: Connected to the database. {"timestamp":"2022-06-30T06:19:30.335Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T06:20:13.225Z"}
info: Connected to the database. {"timestamp":"2022-06-30T06:20:13.250Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T06:21:28.203Z"}
info: Connected to the database. {"timestamp":"2022-06-30T06:21:28.229Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T06:22:30.237Z"}
info: Connected to the database. {"timestamp":"2022-06-30T06:22:30.269Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T06:23:30.950Z"}
info: Connected to the database. {"timestamp":"2022-06-30T06:23:30.982Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T06:23:47.089Z"}
info: Connected to the database. {"timestamp":"2022-06-30T06:23:47.115Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:07:52.758Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:07:52.808Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:08:17.586Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:08:17.616Z"}
error: 
    status - 500 
    message - ReferenceError: id is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:39:38)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T11:11:53.926Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:15:20.388Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:15:20.417Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of null (setting 'isArchived')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:5)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T11:15:23.659Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:16:12.383Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:16:12.415Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of null (setting 'isArchived')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:40:5)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T11:16:19.057Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:16:43.332Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:16:43.365Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:17:40.814Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:17:40.838Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of null (setting 'isArchived')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:40:5)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PATCH 
    IP - ::1
   {"timestamp":"2022-06-30T11:17:49.005Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:18:06.049Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:18:06.073Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of null (setting 'isArchived')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:40:5)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T11:23:56.653Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:31:48.686Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:31:48.714Z"}
error: 
    status - 500 
    message - TypeError: Cannot set properties of null (setting 'isArchived')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:40:8)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T11:31:53.630Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:32:09.347Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:32:09.387Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:35:26.788Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:35:26.822Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:51:19.918Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:51:19.951Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:9)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd849c9fc7b80054328db8/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T11:51:48.125Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:54:46.570Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:54:46.602Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T11:55:51.690Z"}
info: Connected to the database. {"timestamp":"2022-06-30T11:55:51.718Z"}
error: 
    status - 500 
    message - ReferenceError: _id is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:9)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:00:03.636Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:00:31.423Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:00:31.451Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:00:40.426Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:00:40.450Z"}
error: 
    status - 500 
    message - ReferenceError: UserID is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:12)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:00:49.483Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:01:38.034Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:01:38.060Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:19)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:01:41.399Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:01:59.673Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:01:59.705Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:24)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:02:03.845Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:03:30.839Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:03:30.871Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:44:21)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:03:34.191Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:04:59.156Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:04:59.185Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:26)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:05:02.761Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:26)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:05:05.851Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:05:26.119Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:05:26.151Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:07:16.412Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:07:16.437Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '62bd39d644d59b2f9c1197af', UserID: 'arpan@gmail.com' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:07:19.543Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:09:02.105Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:09:02.129Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:11:14.842Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:11:14.867Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:15:59.014Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:15:59.047Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value "{ id: '62bd39d644d59b2f9c1197af' }" (type Object) at path "_id" for model "Note"
    at model.Query.exec (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T12:16:32.211Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:16:56.793Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:16:56.816Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:17:03.441Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:17:03.466Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:17:10.138Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:17:10.167Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:17:14.730Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:17:14.765Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:17:21.163Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:17:21.219Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:21:19.810Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:21:19.840Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:23:13.612Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:23:13.636Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:23:26.663Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:23:26.693Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:26:53.121Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:26:53.147Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:27:16.572Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:27:16.602Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T12:28:17.922Z"}
info: Connected to the database. {"timestamp":"2022-06-30T12:28:17.943Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndDelete (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:2834:19)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:54:29)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isDelete (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:53:24)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:90:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isDelete 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-30T12:28:20.292Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndDelete (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:2834:19)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:54:29)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isDelete (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:53:24)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:90:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isDelete 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-30T12:42:02.749Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T16:50:28.423Z"}
info: Connected to the database. {"timestamp":"2022-06-30T16:50:28.450Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T16:51:42.156Z"}
info: Connected to the database. {"timestamp":"2022-06-30T16:51:42.182Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T16:51:56.937Z"}
info: Connected to the database. {"timestamp":"2022-06-30T16:51:56.962Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T16:52:07.687Z"}
info: Connected to the database. {"timestamp":"2022-06-30T16:52:07.727Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndDelete (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\mongoose\lib\model.js:2834:19)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:54:29)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:53:23)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:90:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isDelete 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-30T16:52:26.809Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T16:53:27.223Z"}
info: Connected to the database. {"timestamp":"2022-06-30T16:53:27.245Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T16:54:28.005Z"}
info: Connected to the database. {"timestamp":"2022-06-30T16:54:28.028Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:56:25)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:53:23)
    at _callee7$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:90:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isDelete 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-30T16:54:52.783Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T16:56:33.881Z"}
info: Connected to the database. {"timestamp":"2022-06-30T16:56:33.917Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T17:13:18.986Z"}
info: Connected to the database. {"timestamp":"2022-06-30T17:13:19.015Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T17:14:01.488Z"}
info: Connected to the database. {"timestamp":"2022-06-30T17:14:01.511Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:20)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T17:14:45.395Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T17:51:16.240Z"}
info: Connected to the database. {"timestamp":"2022-06-30T17:51:16.269Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T17:51:23.421Z"}
info: Connected to the database. {"timestamp":"2022-06-30T17:51:23.445Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:20)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T17:51:50.726Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-30T17:53:05.101Z"}
info: Connected to the database. {"timestamp":"2022-06-30T17:53:05.137Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'UserID')
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:41:25)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:38:28)
    at _callee6$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:77:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bd39d644d59b2f9c1197af/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-30T17:53:08.759Z"}
