info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T02:59:54.771Z"}
info: Connected to the database. {"timestamp":"2022-06-29T02:59:54.815Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:09:23.056Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:09:23.081Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:09:46.468Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:09:46.494Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:10:49.197Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:10:49.224Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:16:14.318Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:16:14.348Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:16:17.954Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:16:17.977Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:17:44.547Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:17:44.575Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:19:54.981Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:19:55.007Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:20:40.360Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:20:40.381Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:21:06.672Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:21:06.703Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:21:23.269Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:21:23.299Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:22:13.053Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:22:13.079Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:22:18.616Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:22:18.647Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:22:49.897Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:22:49.926Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:27:01.566Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:27:01.589Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:42:43.514Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:42:43.543Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:43:20.149Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:43:20.183Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:47:35.038Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:47:35.063Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:48:18.862Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:48:18.895Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T03:48:38.838Z"}
info: Connected to the database. {"timestamp":"2022-06-29T03:48:38.866Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:05:35.909Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:05:35.935Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:05:45.802Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:05:45.830Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:06:31.573Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:06:31.595Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:07:47.963Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:07:47.984Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:08:32.576Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:08:32.598Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:09:50.181Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:09:50.203Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:10:36.263Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:10:36.288Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:11:46.410Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:11:46.433Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:12:57.659Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:12:57.684Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:15:40.786Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:15:40.812Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:18:29.872Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:18:29.895Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:18:34.392Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:18:34.413Z"}
error: 
    status - 500 
    message - ReferenceError: User is not defined
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:20:28)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:20:25)
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:51:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bbcbe135ac8d341c334fae 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-29T04:19:33.776Z"}
error: 
    status - 500 
    message - ReferenceError: User is not defined
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:20:28)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:20:25)
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:51:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bbc746c7b2f324a498982d 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-29T04:23:00.271Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:26:13.765Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:26:13.788Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:27:46.485Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:27:46.510Z"}
error: 
    status - 500 
    message - ReferenceError: User is not defined
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:20:28)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:20:25)
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:51:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bbc746c7b2f324a498982d 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-06-29T04:27:53.318Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:29:48.038Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:29:48.066Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:31:01.854Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:31:01.876Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:32:00.474Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:32:00.495Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:32:33.918Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:32:33.940Z"}
error: 
    status - 500 
    message - ReferenceError: User is not defined
    at _callee5$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:33:30)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.deleteNotes (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/note.service.js:33:27)
    at _callee5$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/note.controller.js:64:40)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/userNotes/62bbc746c7b2f324a498982d 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-06-29T04:33:04.009Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-29T04:34:27.267Z"}
info: Connected to the database. {"timestamp":"2022-06-29T04:34:27.302Z"}
